name: ota_generator
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build: ^2.1.0
  source_gen: ^1.1.1
  source_helper: ^1.3.0
  dio: ^4.0.0
  hive: ^2.0.4
  ota_string: any

dev_dependencies:
  build_test: ^2.1.3
  build_runner: ^2.1.2
  lints: ^1.0.1

