name: ota_generator
description: Source code generator to help create multi-language string translation with update over the air without any charges.
repository: https://github.com/aldychris/ota_string/tree/master/ota_generator
version: 0.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  analyzer: ">=2.5.0  <8.0.0"
  build: ^2.4.1
  source_gen: ^1.4.0
  source_helper: ^1.3.4
  dio: ^5.3.2
  hive: ^2.2.3
  ota_string: ^0.0.5

dev_dependencies:
  build_test: ^2.2.0
  build_runner: ^2.4.6
  lints: ^2.1.1
