name: example
description: Just example
repository: https://github.com/aldychris/ota_string/tree/master/ota_generator/example
version: 0.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  ota_string: ^0.0.5
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: any
  lints: ^2.1.1
  ota_generator: ^0.0.5

dependency_overrides:
  ota_string:
    path: ../../ota_string/
  ota_generator:
    path: ..
