include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning

linter:
  rules:
    - camel_case_types
    - avoid_empty_else
    - provide_deprecation_message
    - prefer_null_aware_operators
    - prefer_if_elements_to_conditional_expressions
    - prefer_foreach
    - prefer_constructors_over_static_methods
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_void_to_null
    - flutter_style_todos
    - file_names
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_new
    - unnecessary_statements
    - unnecessary_this