name: ota_string
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
